# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\plans_console\appTracksDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppTracksDialog(object):
    def setupUi(self, AppTracksDialog):
        AppTracksDialog.setObjectName("AppTracksDialog")
        AppTracksDialog.resize(791, 516)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        AppTracksDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(AppTracksDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AppTracksDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(AppTracksDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(AppTracksDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.tableWidgetAssociated = QtWidgets.QTableWidget(AppTracksDialog)
        self.tableWidgetAssociated.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidgetAssociated.setObjectName("tableWidgetAssociated")
        self.tableWidgetAssociated.setColumnCount(3)
        self.tableWidgetAssociated.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAssociated.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAssociated.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAssociated.setHorizontalHeaderItem(2, item)
        self.tableWidgetAssociated.horizontalHeader().setHighlightSections(False)
        self.tableWidgetAssociated.verticalHeader().setVisible(False)
        self.tableWidgetAssociated.verticalHeader().setDefaultSectionSize(20)
        self.tableWidgetAssociated.verticalHeader().setHighlightSections(False)
        self.tableWidgetAssociated.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_2.addWidget(self.tableWidgetAssociated)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(AppTracksDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.tableWidgetUnassociated = QtWidgets.QTableWidget(AppTracksDialog)
        self.tableWidgetUnassociated.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidgetUnassociated.setObjectName("tableWidgetUnassociated")
        self.tableWidgetUnassociated.setColumnCount(3)
        self.tableWidgetUnassociated.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetUnassociated.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetUnassociated.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetUnassociated.setHorizontalHeaderItem(2, item)
        self.tableWidgetUnassociated.horizontalHeader().setHighlightSections(False)
        self.tableWidgetUnassociated.verticalHeader().setVisible(False)
        self.tableWidgetUnassociated.verticalHeader().setDefaultSectionSize(20)
        self.tableWidgetUnassociated.verticalHeader().setHighlightSections(False)
        self.tableWidgetUnassociated.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_3.addWidget(self.tableWidgetUnassociated)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(AppTracksDialog)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(AppTracksDialog)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.ignoredListWidget = QtWidgets.QListWidget(AppTracksDialog)
        self.ignoredListWidget.setObjectName("ignoredListWidget")
        self.verticalLayout_5.addWidget(self.ignoredListWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AppTracksDialog)
        QtCore.QMetaObject.connectSlotsByName(AppTracksDialog)

    def retranslateUi(self, AppTracksDialog):
        _translate = QtCore.QCoreApplication.translate
        AppTracksDialog.setWindowTitle(_translate("AppTracksDialog", "AppTracks Manager"))
        self.label.setText(_translate("AppTracksDialog", "Use this dialog to view and edit AppTrack/outing associations.\n"
"\n"
"Ideally, if all AppTracks are properly named, and Finished by the app user when done with the assignment, you won\'t need to make any changes here.\n"
"\n"
" - AppTracks with proper titles will automatically be associated with an outing and listed below.\n"
" - AppTracks not associated with any outing will not be shown on generated debrief PDFs.\n"
" - When an AppTrack is Finished, it is converted to a Line and removed from these tables; AppTracks listed here are still being recorded / have not been Finished.\n"
" - AppTracks that are entirely covered by Lines of the same name (remnants of correctly Finished AppTracks) are listed under \'Ignored Duplicates\' for reference, and will not appear on generated debrief PDFs.\n"
"\n"
"Changes here take effect immediately; you can close and reopen this dialog at any time."))
        self.label_2.setText(_translate("AppTracksDialog", "Associated with an outing"))
        item = self.tableWidgetAssociated.horizontalHeaderItem(0)
        item.setText(_translate("AppTracksDialog", "Title"))
        item = self.tableWidgetAssociated.horizontalHeaderItem(1)
        item.setText(_translate("AppTracksDialog", "Outing"))
        item = self.tableWidgetAssociated.horizontalHeaderItem(2)
        item.setText(_translate("AppTracksDialog", "Latest"))
        self.label_3.setText(_translate("AppTracksDialog", "Not associated with an outing"))
        item = self.tableWidgetUnassociated.horizontalHeaderItem(0)
        item.setText(_translate("AppTracksDialog", "Title"))
        item = self.tableWidgetUnassociated.horizontalHeaderItem(1)
        item.setText(_translate("AppTracksDialog", "Outing"))
        item = self.tableWidgetUnassociated.horizontalHeaderItem(2)
        item.setText(_translate("AppTracksDialog", "Latest"))
        self.label_4.setText(_translate("AppTracksDialog", "Ignored Duplicates"))
