# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\plans_console\debrief.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebriefDialog(object):
    def setupUi(self, DebriefDialog):
        DebriefDialog.setObjectName("DebriefDialog")
        DebriefDialog.resize(558, 300)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(DebriefDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 521, 258))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sourceURLLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.sourceURLLabel.setObjectName("sourceURLLabel")
        self.horizontalLayout_2.addWidget(self.sourceURLLabel)
        self.sourceURLField = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.sourceURLField.setText("")
        self.sourceURLField.setObjectName("sourceURLField")
        self.horizontalLayout_2.addWidget(self.sourceURLField)
        self.sourceMapLight = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceMapLight.sizePolicy().hasHeightForWidth())
        self.sourceMapLight.setSizePolicy(sizePolicy)
        self.sourceMapLight.setMaximumSize(QtCore.QSize(20, 16777215))
        self.sourceMapLight.setObjectName("sourceMapLight")
        self.horizontalLayout_2.addWidget(self.sourceMapLight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.targetMapLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.targetMapLabel.setObjectName("targetMapLabel")
        self.horizontalLayout_3.addWidget(self.targetMapLabel)
        self.debriefURLField = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.debriefURLField.setObjectName("debriefURLField")
        self.horizontalLayout_3.addWidget(self.debriefURLField)
        self.debriefMapLight = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debriefMapLight.sizePolicy().hasHeightForWidth())
        self.debriefMapLight.setSizePolicy(sizePolicy)
        self.debriefMapLight.setMaximumSize(QtCore.QSize(20, 16777215))
        self.debriefMapLight.setObjectName("debriefMapLight")
        self.horizontalLayout_3.addWidget(self.debriefMapLight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tableWidget)

        self.retranslateUi(DebriefDialog)
        QtCore.QMetaObject.connectSlotsByName(DebriefDialog)

    def retranslateUi(self, DebriefDialog):
        _translate = QtCore.QCoreApplication.translate
        DebriefDialog.setWindowTitle(_translate("DebriefDialog", "Dialog"))
        self.sourceURLLabel.setText(_translate("DebriefDialog", "Source Map URL"))
        self.sourceURLField.setPlaceholderText(_translate("DebriefDialog", "http(s)://sourceMapURL"))
        self.targetMapLabel.setText(_translate("DebriefDialog", "Debrief Map URL"))
        self.debriefURLField.setPlaceholderText(_translate("DebriefDialog", "http(s)://debriefMapURL"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DebriefDialog", "Outing"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DebriefDialog", "Tracks"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DebriefDialog", "Latest"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DebriefDialog", "Print"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DebriefDialog", "Rebuild"))
