# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caver\Documents\GitHub\plans_console\debriefOptionsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebriefOptionsDialog(object):
    def setupUi(self, DebriefOptionsDialog):
        DebriefOptionsDialog.setObjectName("DebriefOptionsDialog")
        DebriefOptionsDialog.resize(463, 345)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        DebriefOptionsDialog.setFont(font)
        self.topLayout = QtWidgets.QVBoxLayout(DebriefOptionsDialog)
        self.topLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.topLayout.setObjectName("topLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DebriefOptionsDialog)
        self.groupBox.setObjectName("groupBox")
        self.pdfGroupBoxLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.pdfGroupBoxLayout.setObjectName("pdfGroupBoxLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.layerComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerComboBox.sizePolicy().hasHeightForWidth())
        self.layerComboBox.setSizePolicy(sizePolicy)
        self.layerComboBox.setObjectName("layerComboBox")
        self.layerComboBox.addItem("")
        self.layerComboBox.addItem("")
        self.layerComboBox.addItem("")
        self.layerComboBox.addItem("")
        self.layerComboBox.addItem("")
        self.layerComboBox.addItem("")
        self.layerComboBox.addItem("")
        self.horizontalLayout.addWidget(self.layerComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.mapBuilderOverlayCheckbox = QtWidgets.QCheckBox(self.groupBox)
        self.mapBuilderOverlayCheckbox.setObjectName("mapBuilderOverlayCheckbox")
        self.verticalLayout.addWidget(self.mapBuilderOverlayCheckbox)
        self.contoursCheckbox = QtWidgets.QCheckBox(self.groupBox)
        self.contoursCheckbox.setObjectName("contoursCheckbox")
        self.verticalLayout.addWidget(self.contoursCheckbox)
        self.slopeShadingCheckbox = QtWidgets.QCheckBox(self.groupBox)
        self.slopeShadingCheckbox.setObjectName("slopeShadingCheckbox")
        self.verticalLayout.addWidget(self.slopeShadingCheckbox)
        self.utmGridCheckbox = QtWidgets.QCheckBox(self.groupBox)
        self.utmGridCheckbox.setChecked(True)
        self.utmGridCheckbox.setObjectName("utmGridCheckbox")
        self.verticalLayout.addWidget(self.utmGridCheckbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pdfGroupBoxLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rebuildAllButton = QtWidgets.QPushButton(DebriefOptionsDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plans_console/reload-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rebuildAllButton.setIcon(icon)
        self.rebuildAllButton.setObjectName("rebuildAllButton")
        self.horizontalLayout_3.addWidget(self.rebuildAllButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DebriefOptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.topLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(DebriefOptionsDialog)
        self.buttonBox.accepted.connect(DebriefOptionsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DebriefOptionsDialog.reject) # type: ignore
        self.layerComboBox.currentTextChanged['QString'].connect(DebriefOptionsDialog.onLayerComboChange) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DebriefOptionsDialog)

    def retranslateUi(self, DebriefOptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        DebriefOptionsDialog.setWindowTitle(_translate("DebriefOptionsDialog", "Debrief Options"))
        self.groupBox.setTitle(_translate("DebriefOptionsDialog", "PDF Options"))
        self.label.setText(_translate("DebriefOptionsDialog", "Basemap Layer"))
        self.layerComboBox.setItemText(0, _translate("DebriefOptionsDialog", "Scanned Topo (USGS 7.5\')"))
        self.layerComboBox.setItemText(1, _translate("DebriefOptionsDialog", "Forest Service (2016 - Green)"))
        self.layerComboBox.setItemText(2, _translate("DebriefOptionsDialog", "Forest Service (2016 - White)"))
        self.layerComboBox.setItemText(3, _translate("DebriefOptionsDialog", "Forest Service (2013 - White)"))
        self.layerComboBox.setItemText(4, _translate("DebriefOptionsDialog", "Imagery (NAIP)"))
        self.layerComboBox.setItemText(5, _translate("DebriefOptionsDialog", "* MapBuilder Topo"))
        self.layerComboBox.setItemText(6, _translate("DebriefOptionsDialog", "* MapBuilder Hybrid"))
        self.mapBuilderOverlayCheckbox.setText(_translate("DebriefOptionsDialog", "* MapBuilder Overlay"))
        self.contoursCheckbox.setText(_translate("DebriefOptionsDialog", "* Contours"))
        self.slopeShadingCheckbox.setText(_translate("DebriefOptionsDialog", "* Slope Angle Shading (fixed)"))
        self.utmGridCheckbox.setText(_translate("DebriefOptionsDialog", "Show UTM Grid (at auto-interval)"))
        self.label_2.setText(_translate("DebriefOptionsDialog", "* These layers may cause slower PDF generation.  For fastest PDF generation, use static layers (USGS, USFS, NAIP, etc.) with no overlays."))
        self.rebuildAllButton.setText(_translate("DebriefOptionsDialog", "  Rebuild Entire Debrief Map"))
import plans_console_rc
