# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debriefMapDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebriefMapDialog(object):
    def setupUi(self, DebriefMapDialog):
        DebriefMapDialog.setObjectName("DebriefMapDialog")
        DebriefMapDialog.resize(360, 279)
        self.buttonBox = QtWidgets.QDialogButtonBox(DebriefMapDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(DebriefMapDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 321, 51))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DebriefMapDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 210, 91, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.urlField = QtWidgets.QLineEdit(DebriefMapDialog)
        self.urlField.setEnabled(False)
        self.urlField.setGeometry(QtCore.QRect(110, 210, 241, 22))
        self.urlField.setObjectName("urlField")
        self.mapIDField = QtWidgets.QLineEdit(DebriefMapDialog)
        self.mapIDField.setGeometry(QtCore.QRect(200, 120, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.mapIDField.setFont(font)
        self.mapIDField.setText("")
        self.mapIDField.setObjectName("mapIDField")
        self.label_3 = QtWidgets.QLabel(DebriefMapDialog)
        self.label_3.setGeometry(QtCore.QRect(200, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(DebriefMapDialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 161, 131))
        self.groupBox.setObjectName("groupBox")
        self.domainAndPortOtherField = QtWidgets.QLineEdit(self.groupBox)
        self.domainAndPortOtherField.setEnabled(False)
        self.domainAndPortOtherField.setGeometry(QtCore.QRect(40, 100, 113, 22))
        self.domainAndPortOtherField.setObjectName("domainAndPortOtherField")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 50, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.domainAndPortButtonGroup = QtWidgets.QButtonGroup(DebriefMapDialog)
        self.domainAndPortButtonGroup.setObjectName("domainAndPortButtonGroup")
        self.domainAndPortButtonGroup.addButton(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 95, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.domainAndPortButtonGroup.addButton(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 80, 95, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.domainAndPortButtonGroup.addButton(self.radioButton_3)
        self.label_4 = QtWidgets.QLabel(DebriefMapDialog)
        self.label_4.setGeometry(QtCore.QRect(200, 150, 71, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(DebriefMapDialog)
        self.buttonBox.accepted.connect(DebriefMapDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DebriefMapDialog.reject) # type: ignore
        self.mapIDField.textChanged['QString'].connect(DebriefMapDialog.urlChanged) # type: ignore
        self.domainAndPortOtherField.textChanged['QString'].connect(DebriefMapDialog.urlChanged) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DebriefMapDialog)

    def retranslateUi(self, DebriefMapDialog):
        _translate = QtCore.QCoreApplication.translate
        DebriefMapDialog.setWindowTitle(_translate("DebriefMapDialog", "Debrief Map"))
        self.label.setText(_translate("DebriefMapDialog", "No debrief map has been specified yet, so the Debrief Map Generator is not running.  To begin the Debrief Map Generator, specify the URL of an existing debreif map."))
        self.label_2.setText(_translate("DebriefMapDialog", "Debrief Map URL:"))
        self.mapIDField.setPlaceholderText(_translate("DebriefMapDialog", "A1B2C"))
        self.label_3.setText(_translate("DebriefMapDialog", "Debrief Map ID"))
        self.groupBox.setTitle(_translate("DebriefMapDialog", "Domain and Port"))
        self.domainAndPortOtherField.setPlaceholderText(_translate("DebriefMapDialog", "myServer:8080"))
        self.radioButton_2.setText(_translate("DebriefMapDialog", "sartopo.com"))
        self.radioButton.setText(_translate("DebriefMapDialog", "localhost:8080"))
        self.radioButton_3.setText(_translate("DebriefMapDialog", "Other"))
        self.label_4.setText(_translate("DebriefMapDialog", "3-5 characters"))
